---
- name: Creates deploy dir
  file:
    path: /srv/deploy
    state: directory

- name: Create a music link
  ansible.builtin.file:
    src: /home/{{ user }}/music
    dest: /root/music
    state: link
  when: user != 'root'

- name: Create a video link
  ansible.builtin.file:
    src: /home/{{ user }}/video
    dest: /root/video
    state: link
  when: user != 'root'

- name: move video
  shell: mv /root/video/video.mp4 /root/video/play.mp4
  notify:
   - restart ffmpeg
  ignore_errors: yes

- name: edit bashrc
  lineinfile:
    path: /root/.bashrc
    regexp: '^alias next'
    line: alias next='docker exec --tty mpd mpc next'
    state: present

- name: copy entrypoint.sh
  copy:
    src="entrypoint.sh"
    dest=/srv/deploy/entrypoint.sh
    owner=root
    group=root
    mode=0755

- name: template docker
  template: 
    src="docker-compose.yaml.j2" 
    dest=/srv/deploy/docker-compose.yaml
    owner=root 
    group=root 
    mode=0644

- name: deploy
  docker_compose:
    project_src: /srv/deploy/
    state: present
    remove_orphans: yes
   
- name: update playlist
  shell: cd /root/music/ && ls -1 *.mp3 > /var/lib/docker/volumes/deploy_mpd_playlists/_data/playlist.m3u
  notify:
   - restart ffmpeg

- name: load playlist
  shell: docker exec --tty mpd mpc repeat on && docker exec --tty mpd mpc random on && docker exec --tty mpd mpc clear && docker exec --tty mpd mpc update && docker exec --tty mpd mpc load playlist && docker exec --tty mpd mpc play
  notify:
   - restart ffmpeg
