- name: template systemd unit
  template:
    src: track_update.service.j2
    dest: /etc/systemd/system/track_update.service
  notify:
   - daemon_reload track_update

- name: enable track_update
  service:
    name: track_update
    state: started
    daemon_reload: true
    enabled: true
